// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug  7 2025 16:45:12 IST (Aug  7 2025 11:15:12 UTC)

// Verification Directory fv/full_adder 

module full_adder(A, B, Cin, Sum, Cout);
  input A, B, Cin;
  output Sum, Cout;
  wire A, B, Cin;
  wire Sum, Cout;
  wire n_0, n_1;
  ADDFX1 g87__2398(.A (B), .B (A), .CI (Cin), .CO (n_0), .S (n_1));
  BUFX6 drc_bufs(.A (n_1), .Y (Sum));
  BUFX6 drc_bufs90(.A (n_0), .Y (Cout));
endmodule
