/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cadence1)
#  Generated on:      Thu Aug 21 17:22:00 2025
#  Design:            full_adder
#  Command:           saveNetlist routing_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 16 2025 10:07:15 IST (Aug 16 2025 04:37:15 UTC)
// Verification Directory fv/full_adder 
module full_adder (
	A, 
	B, 
	Cin, 
	Sum, 
	Cout);
   input A;
   input B;
   input Cin;
   output Sum;
   output Cout;

   // Internal wires
   wire FE_OFN1_Cout;
   wire FE_OFN0_Sum;

   CLKBUFX8 FE_OFC1_Cout (.A(FE_OFN1_Cout),
	.Y(Cout));
   CLKBUFX8 FE_OFC0_Sum (.A(FE_OFN0_Sum),
	.Y(Sum));
   ADDFX1 g87__2398 (.A(B),
	.B(A),
	.CI(Cin),
	.CO(FE_OFN1_Cout),
	.S(FE_OFN0_Sum));
endmodule
